services:
  lms_postgres:
    image: postgres:15-alpine
    container_name: lms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: lms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lms_redis:
    image: redis:7-alpine
    container_name: lms_redis
    restart: always
    ports:
      - "6379:6379"

  lms_backend:
    build: .
    container_name: lms_backend
    restart: always
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@lms_postgres:5432/lms_db?schema=public"
    env_file:
      - path: .env
        required: false
    depends_on:
      - lms_postgres
      - lms_redis

volumes:
  postgres_data:
